# Generated by Django 4.1 on 2022-08-15 02:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=100)),
                ('html', models.TextField()),
                ('css', models.TextField()),
                ('thumbnails', models.ImageField(default='https://tailwindui.com/img/ecommerce-images/home-page-02-edition-01.jpg', upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='UserTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=100)),
                ('html', models.TextField()),
                ('css', models.TextField()),
                ('thumbnails', models.ImageField(blank=True, default='none', null=True, upload_to='')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='usertemplates', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
