# Generated by Django 4.1 on 2022-08-11 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=100)),
                ('html', models.TextField()),
                ('css', models.TextField()),
                ('thumbnails', models.ImageField(default='https://tailwindui.com/img/ecommerce-images/home-page-02-edition-01.jpg', upload_to='')),
            ],
        ),
    ]
