# Generated by Django 4.1 on 2022-08-12 02:00

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('builder', '0002_usertemplates'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserTemplates',
            new_name='UserTemplate',
        ),
    ]
