# Generated by Django 4.1 on 2022-08-12 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0003_rename_usertemplates_usertemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertemplate',
            name='parent_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='builder.template'),
        ),
    ]
