# Generated by Django 4.1 on 2022-08-12 21:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0004_usertemplate_parent_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertemplate',
            name='parent_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usertemplates', to='builder.template'),
        ),
        migrations.AlterField(
            model_name='usertemplate',
            name='thumbnails',
            field=models.ImageField(default='default', upload_to=''),
        ),
    ]
