# Generated by Django 4.1 on 2022-08-12 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0005_alter_usertemplate_parent_template_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertemplate',
            name='thumbnails',
            field=models.ImageField(default='default.png', upload_to=''),
        ),
    ]
