# Generated by Django 4.1 on 2022-08-12 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0008_alter_usertemplate_thumbnails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertemplate',
            name='thumbnails',
            field=models.ImageField(default='Default.png', upload_to='default/'),
        ),
    ]
