# Generated by Django 4.1 on 2022-08-12 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0012_alter_usertemplate_thumbnails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertemplate',
            name='thumbnails',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
